/**
 * EXPRESSÕES ORAIS DO PORTUGUÊS BRASILEIRO → paráfrase em português claro.
 *
 * Por que paráfrase NA ORIGEM e não tradução direta: a edição leve traduz com motores de frase
 * (Chrome Translator, opus-mt, MyMemory) que vertem "pois é" em "so it is" e "a gente" em "the
 * people". Reescrever a gíria em português "de dicionário" ANTES de traduzir faz qualquer motor
 * acertar o sentido — é o que dá para fazer honestamente offline, sem LLM.
 *
 * `FRASES_INTEIRAS` cobre a fala que é SÓ a expressão ("valeu!") — aí a tradução vai pronta.
 */

/** Substituições dentro da frase (minúsculas; a caixa da inicial é preservada na aplicação). */
export const PARAFRASES: ReadonlyArray<readonly [string, string]> = [
  ['pois é', 'é verdade'],
  ['tô ligado', 'entendi'],
  ['to ligado', 'entendi'],
  ['tá ligado', 'entende'],
  ['ta ligado', 'entende'],
  ['de boa', 'tranquilo'],
  ['de boas', 'tranquilo'],
  ['numa boa', 'tranquilamente'],
  ['dar certo', 'funcionar'],
  ['deu certo', 'funcionou'],
  ['dá certo', 'funciona'],
  ['deu ruim', 'deu errado'],
  ['ficar de olho', 'observar'],
  ['fica de olho', 'observe'],
  ['puxar assunto', 'começar uma conversa'],
  ['puxar papo', 'começar uma conversa'],
  ['bater um papo', 'conversar'],
  ['bater papo', 'conversar'],
  ['trocar uma ideia', 'conversar'],
  ['trocar ideia', 'conversar'],
  ['mandar bem', 'ir muito bem'],
  ['mandou bem', 'foi muito bem'],
  ['mandei bem', 'fui muito bem'],
  ['fazer uma vaquinha', 'juntar dinheiro entre todos'],
  ['pagar mico', 'passar vergonha'],
  ['paguei mico', 'passei vergonha'],
  ['encher o saco', 'incomodar'],
  ['enche o saco', 'incomoda'],
  ['botar fé', 'acreditar'],
  ['bota fé', 'acredite'],
  ['sem noção', 'absurdo'],
  ['cara de pau', 'sem vergonha'],
  ['pra caramba', 'muito'],
  ['pra caralho', 'muito'],
  ['pra cacete', 'muito'],
  ['à beça', 'muito'],
  ['um monte de', 'muitos'],
  ['um montão de', 'muitos'],
  ['nem a pau', 'de jeito nenhum'],
  ['nem ferrando', 'de jeito nenhum'],
  ['nem pensar', 'de jeito nenhum'],
  ['tanto faz', 'não importa'],
  ['fazer as pazes', 'reconciliar-se'],
  ['dar um jeito', 'resolver'],
  ['dá um jeito', 'resolve'],
  ['deu um jeito', 'resolveu'],
  ['quebrar um galho', 'ajudar'],
  ['quebra um galho', 'ajuda'],
  ['quebrou um galho', 'ajudou'],
  ['pisar na bola', 'errar'],
  ['pisou na bola', 'errou'],
  ['pisei na bola', 'errei'],
  ['viajar na maionese', 'falar bobagem'],
  ['tá de brincadeira', 'está brincando'],
  ['ta de brincadeira', 'está brincando'],
  ['sei lá', 'não sei'],
  ['que nem', 'como'],
  ['massa', 'ótimo'],
  ['maneiro', 'ótimo'],
  ['daora', 'ótimo'],
  ['da hora', 'ótimo'],
  ['irado', 'ótimo'],
  ['bacana', 'legal'],
  ['galera', 'pessoal'],
  ['véi', 'cara'],
  ['grana', 'dinheiro'],
  ['bufunfa', 'dinheiro'],
  ['rolê', 'passeio'],
  ['treta', 'briga'],
  ['zoeira', 'brincadeira'],
  ['zoar', 'brincar'],
  ['trampo', 'trabalho'],
  ['trampar', 'trabalhar'],
  ['perrengue', 'situação difícil'],
  ['bagulho', 'coisa'],
  ['curtir', 'gostar de'],
  ['curti', 'gostei de'],
  ['curto', 'gosto de'],
  ['sacou', 'entendeu'],
  ['saquei', 'entendi'],
  ['sacar', 'entender'],
]

/** Falas que SÃO a expressão inteira: já saem traduzidas, por idioma-alvo. */
export const FRASES_INTEIRAS: Readonly<Record<string, ReadonlyArray<readonly [string, string]>>> = {
  en: [
    ['valeu', 'Thanks!'],
    ['pois é', 'Yeah, exactly.'],
    ['beleza', 'All good.'],
    ['beleza?', 'All good?'],
    ['tá bom', 'Okay.'],
    ['ta bom', 'Okay.'],
    ['tá bem', 'Okay.'],
    ['tudo bem', 'All good.'],
    ['tudo bem?', 'How are you?'],
    ['e aí', 'Hey, what’s up?'],
    ['e aí?', 'Hey, what’s up?'],
    ['fala aí', 'Hey, what’s up?'],
    ['tô ligado', 'Got it.'],
    ['to ligado', 'Got it.'],
    ['de boa', 'No worries.'],
    ['sei lá', 'I don’t know.'],
    ['sem problema', 'No problem.'],
    ['imagina', 'No problem at all.'],
    ['nossa', 'Wow.'],
    ['eita', 'Whoa.'],
    ['caramba', 'Wow.'],
    ['show', 'Awesome.'],
    ['massa', 'Awesome.'],
    ['top', 'Awesome.'],
    ['bora', 'Let’s go.'],
    ['partiu', 'Let’s go.'],
    ['tanto faz', 'Whatever works.'],
    ['nem pensar', 'No way.'],
    ['com certeza', 'Absolutely.'],
    ['pode crer', 'For sure.'],
    ['fechou', 'Deal.'],
    ['tamo junto', 'I’ve got your back.'],
    ['deixa comigo', 'Leave it to me.'],
    ['só um minuto', 'Just a minute.'],
    ['peraí', 'Hold on.'],
    ['pera aí', 'Hold on.'],
    ['espera aí', 'Hold on.'],
    ['foi mal', 'My bad.'],
    ['desculpa', 'Sorry.'],
    ['que pena', 'What a shame.'],
    ['que legal', 'That’s cool.'],
    ['que bom', 'That’s great.'],
    ['boa', 'Nice one.'],
    ['manda', 'Go ahead.'],
    ['pode falar', 'Go ahead.'],
    ['então tá', 'Alright then.'],
    ['a gente se fala', 'Talk to you later.'],
    ['até mais', 'See you later.'],
    ['falou', 'Later!'],
    ['tchau', 'Bye.'],
    ['vamos nessa', 'Let’s do it.'],
  ],
}
